server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        contactCreatedOut:
          destination: ContactCreatedTopic
          contentType: application/json

        contactUpdatedOut:
          destination: ContactUpdatedTopic
          contentType: application/json

        contactRemovedOut:
          destination: ContactRemovedTopic
          contentType: application/json
  datasource:
    url: jdbc:postgresql://localhost:5432/contact-db
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
      show_sql: true
    hibernate:
      ddl-auto: update

